In [4]:
function crowdingDist(objs)
    crowdDist = zeros(Float64, size(objs)[2])
    for i in 1:size(objs)[1]
        v = sortperm(objs[i,:], rev=true)
        println(objs[i,:])
        println(v)
        crowdDist[v[1]] = crowdDist[v[1]] + 2*objs[i,v[1]]
        crowdDist[v[end]] = crowdDist[v[end]] + 2*objs[i,v[end]]
        for j in 2:length(crowdDist)-1
            crowdDist[v[j]] = crowdDist[v[j]] + (objs[i,v[j-1]] + objs[i,v[j+1]])
        end
    end
    return crowdDist
end

crowdingDist (generic function with 1 method)

In [5]:
a = rand(4,5)

4×5 Array{Float64,2}:
 0.368349  0.422663  0.111659  0.940827  0.162422
 0.152559  0.694914  0.490746  0.651641  0.269333
 0.998905  0.238633  0.113123  0.798093  0.54954 
 0.631719  0.30551   0.212629  0.821981  0.325008

In [6]:
metric = crowdingDist(a)

[0.368349, 0.422663, 0.111659, 0.940827, 0.162422]
[4, 2, 1, 5, 3]
[0.152559, 0.694914, 0.490746, 0.651641, 0.269333]
[2, 4, 3, 5, 1]
[0.998905, 0.238633, 0.113123, 0.798093, 0.54954]
[1, 4, 5, 2, 3]
[0.631719, 0.30551, 0.212629, 0.821981, 0.325008]
[4, 1, 5, 2, 3]


5-element Array{Float64,1}:
 4.035002983374684 
 3.899304517739364 
 1.795798152766333 
 6.25972109293612  
 3.0972674050814994

In [44]:
metric = [15,18,25,18]

4-element Array{Int64,1}:
 15
 18
 25
 18

In [45]:
function nds(metric)
    ndsArchive = Array{Int64,1}[]
    dominated = zeros(Int64, length(metric))
    dominates = Array{Int64}[]
    tempnds = []
    for i in 1:length(metric)
        tempDom = []
        for j in 1:length(metric)
            if metric[i] > metric[j]
                push!(tempDom, j)
            elseif metric[i] < metric[j]
                dominated[i] = dominated[i] + 1
            end
        end
        push!(dominates, tempDom)
        if dominated[i] == 0
            push!(tempnds, i)
        end
    end
    push!(ndsArchive, tempnds)
    i = 1
    while length(ndsArchive[i]) != 0
        tempndsnext = []
        tempndscurr = ndsArchive[i]
        for j in 1:length(tempndscurr)
            p = tempndscurr[j]
            currSet = dominates[p]
            for k in 1:length(currSet)
                q = currSet[k]
                dominated[q] = dominated[q] - 1
                if dominated[q] == 0
                    push!(tempndsnext, q)
                end
            end
        end
        push!(ndsArchive, tempndsnext)
        i = i + 1
    end
    return ndsArchive
end

nds (generic function with 1 method)

In [46]:
nds(metric)

Any[]
Any[1]
Any[1, 2, 4]
Any[1]
Array{Int64,N} where N[[], [1], [1, 2, 4], [1]]
Array{Int64,1}[[3]]


4-element Array{Array{Int64,1},1}:
 [3]   
 [2, 4]
 [1]   
 []    

In [9]:
dominates = Array{Int64}[]

0-element Array{Array{Int64,N} where N,1}

In [21]:
temp = []

0-element Array{Any,1}

In [15]:
push!(dominates,[1,2,3])

3-element Array{Array{Int64,N} where N,1}:
 [1]      
 [1, 2]   
 [1, 2, 3]

In [18]:
print(dominates[3])

[1, 2, 3]

In [24]:
push!(temp,3)

3-element Array{Any,1}:
 1
 2
 3